# Cloudflare Pages 配置
name = "gpt4o-images"
pages_build_output_dir = "dist"

# 环境变量
[vars]
VITE_GOOGLE_CLIENT_ID = "817380442699-icblni9qcb7mvcapmedojcffkcq01toi.apps.googleusercontent.com"

# 自定义域名配置 (需要在Cloudflare DNS中设置)
# [env.production]
# routes = [{pattern = "gpt4o-images.example.com", custom_domain = true}]
